<?php
/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

*/

function fibo($maximumFibo){
   //current fibo holder 	
   $i = 1;
   //previous fibo holder
   $j = 0;
   //Sum of all even-fibo numbers below the maximumFibo passed
   $sum =0;
   //loop
   for($i; $i<$maximumFibo; $i+=$j){
        //is current fibo an even number?
	if($i%2==0)
	   $sum+=$i;
	$j=$i-$j;
     
   }
   echo 'The sum of all even-fibo numbers below '.$maximumFibo.' is '.$sum. "\t\n";

}


fibo(4000000);
